Fix the tutorial
Originate/exosphere pull request #231
Opened 2017-05-13 03:27 UTC by kevgo

Makes the tutorial run again. I am switching to longer but more unambiguous command-line parameters for exo-add. I think that's fine since they will only be used in scripts.

2017-05-13 03:27 UTC, kevgo commented on .travis.yml
> +  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
updates to the latest docker

2017-05-15 16:06 UTC, hugoesthere approved these changes

2017-05-15 16:31 UTC, trushton requested changes

2017-05-15 16:31 UTC, trushton commented on exo-add/src/cli.ls
>    template-name = command-line-args['template']
~~command-line-args['template']~~ 👎 

command-line-args['template-name'] 👍

2017-05-15 19:18 UTC, trushton commented
@kevgo I fixed the one error that was causing failures, but now its back to where things were before with the `write EPIPE` errors

2017-05-15 20:17 UTC, trushton approved these changes

2017-05-15 20:25 UTC, kevgo commented on exo-add/src/cli.ls
>    template-name = command-line-args['template']
@trushton thanks for fixing this. Do the tests run locally on your machine? On my machine they fail now.

2017-05-15 20:25 UTC, kevgo commented on exo-add/src/cli.ls
>    template-name = command-line-args['template']
That's why I didn't do this change before.

2017-05-15 20:55 UTC, kevgo commented on exo-add/src/cli.ls
>    template-name = command-line-args['template']
Correction: Travis worked, so the setup must have been on my machine. Upgrading Node fixed the issue. This works now. Thanks for the contribution!

2017-05-15 21:10 UTC, closed without merging