Add bastion sg to rds sg
Originate/exosphere pull request #701
Opened 2017-10-24 21:23 UTC by hugobho

Not sure if we should be doing this for every case, but thought I'd put up a PR for it.

2017-10-24 21:31 UTC, alexdavid commented
Just talked to @chrizkim about this and he suggests that we don't do this. If needed we can double port forward to the ecs cluster.

2017-10-24 21:32 UTC, hugobho commented
👍

2017-10-24 21:46 UTC, alexdavid approved these changes

2017-10-24 21:50 UTC, alexdavid requested changes

2017-10-24 21:50 UTC, alexdavid commented on src/terraform/modules/aws/dependencies/rds/rds.tf
> +    protocol        = -1
I think this should be
```
from_port       = 5432
to_port         = 5432
protocol        = 6
```

2017-10-24 21:51 UTC, alexdavid commented on src/terraform/modules/aws/dependencies/rds/rds.tf
> +    protocol        = -1
You can also use 
```
protocol        = "tcp"
```
I think

2017-10-25 17:33 UTC, hugobho commented
@alexdavid comments addressed

2017-10-25 18:33 UTC, alexdavid approved these changes

2017-10-25 18:34 UTC, merged